# Generated by Django 3.2.16 on 2023-01-29 02:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0002_auto_20230128_2239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journal',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='journal_dish_intermediary',
            name='journal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='journal_dish_intermediary', to='journal.journal'),
        ),
    ]
