# Generated by Django 3.2.16 on 2023-01-29 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0003_auto_20230129_0238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journal',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
