# Generated by Django 3.2.16 on 2023-01-29 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0004_alter_journal_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journal',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
