# Generated by Django 3.2.16 on 2023-02-07 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0007_alter_journal_calories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dish',
            name='calories',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='dish',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='journal',
            name='calories',
            field=models.IntegerField(default=0),
        ),
    ]
