# Generated by Django 3.2.16 on 2023-03-13 22:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0009_auto_20230313_2053'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='weight',
            name='user',
        ),
        migrations.AddField(
            model_name='weight',
            name='profile',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='journal.profile'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='weights',
            field=models.ManyToManyField(blank=True, related_name='weights', to='journal.Weight'),
        ),
    ]
