# Generated by Django 3.2.16 on 2023-03-13 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0013_alter_weight_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='initial_weight',
            field=models.IntegerField(default=0),
        ),
    ]
