# Generated by Django 3.2.16 on 2023-03-14 00:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0014_profile_initial_weight'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='initial_weight',
        ),
    ]
