# Generated by Django 3.2.16 on 2023-03-14 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0015_remove_profile_initial_weight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='weights',
            field=models.ManyToManyField(blank=True, null=True, related_name='weights', to='journal.Weight'),
        ),
    ]
