# Generated by Django 3.2.16 on 2023-03-14 02:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0017_remove_weight_profile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='weight',
            options={'ordering': ['date']},
        ),
    ]
