# Generated by Django 3.2.16 on 2023-03-14 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0018_alter_weight_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='goal_weight',
            field=models.IntegerField(default=160),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='starting_weight',
            field=models.IntegerField(default=210),
            preserve_default=False,
        ),
    ]
